unsigned short points_bitmap[] = {BG, BG,BG,BG,BG,BL,BL,BL,BG,BG,BG,BG,BG,
									BG, BG,BG,BL,BL,BL,BL,BL,BL,BL,BG,BG,BG,
									BG, BG,BL,BL,BL,BL,BL,BL,BL,BL,BL,BG,BG,
									BG, BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BG,
									BG, BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BG,
									BL, BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
									BL, BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,
									BG, BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BG,
									BG, BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BG,
									BG, BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BL,BG,
									BG, BG,BL,BL,BL,BL,BL,BL,BL,BL,BL,BG,BG,
									BG, BG,BG,BL,BL,BL,BL,BL,BL,BL,BG,BG,BG,
									BG, BG,BG,BG,BG,BL,BL,BL,BG,BG,BG,BG,BG };

unsigned short finish_bitmap[] = {GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,
																	GR, GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR,GR}; 

unsigned short pacman_bitmap[] = {BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, BG, BG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, BG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, YG,BG, BG, BG, BG,
																	BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, YG,BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, YG,YG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, YG,YG, YG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, 
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, YG,YG, YG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, YG,YG, BG, BG, BG,
																	BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, YG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, BG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, YG, BG,BG, BG, BG, BG,
																	BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, YG, YG, YG, YG, YG,YG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, YG, YG, YG, YG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, YG, YG, YG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, YG, YG, YG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG
	
																	};
	
	unsigned short pacman_bitmap1[] = {	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, BG, BG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, BG, BG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, BG, BG, YG,BG, BG, BG, BG,
																	BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, 
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG,YG, YG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, YG, YG, YG, YG, YG,YG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, YG, YG, YG, YG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG, YG, YG, YG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, YG, YG, YG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, YG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
	
																	};							

																	
	unsigned short ghost_bitmap[] = {	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																		BG, BG, WH, BG, BG, BG, BG, BG, WH, BG, BG, BG, BG, BG, WH, BG, BG, BG, BG, BG, WH, BG, BG, BG, BG, BG, WH, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, WH, WH, WH, BG, BG, BG, WH, WH, WH, BG, BG, BG, WH, WH, WH, BG, BG, BG, WH, WH, WH, BG, BG, BG, WH, WH, WH,BG, BG, WH, WH,BG, BG, BG, BG,
																	BG, WH, WH, WH, WH, BG, WH, WH, WH, WH, WH, BG, WH, WH, WH, WH, WH, BG, WH, WH, WH, WH, WH, BG, WH, WH, WH, WH,WH, BG, WH, WH,BG, BG, BG, BG,
																	BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, WH, WH, BG,BG, BG, BG, BG,
																	BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, WH, WH, BG,BG, BG, BG, BG,
																	BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, WH, WH, BG,BG, BG, BG, BG,
																	BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, WH, WH, BG,BG, BG, BG, BG,
																	BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, WH, BG, BG,BG, BG, BG, BG,																	
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG, WH, WH, WH, WH, BG, BG, WH, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,																	
																	BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG, BG, BG, WH, WH, BG, BG, BG, BG, WH, WH, WH, WH, WH,WH, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG, BG, BG, WH, WH, BG, BG, BG, BG, WH, WH, WH, WH, WH,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG, WH, WH, WH, WH, BG, BG, WH, WH, WH, WH, WH, WH,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, WH, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, WH, WH, WH, WH, WH, WH, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
	
																	};

	
	unsigned short erase_bitmap[] = {BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG,
																	BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG, BG,BG, BG, BG, BG,BG, BG, BG, BG
																	
};
